# Generated by Django 3.1.3 on 2020-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=2500)),
            ],
        ),
    ]
